### ISSUE TITLE
config 配置管理

### ISSUE THREAD

**Issue by fengzilong** [kaola-fed/megalo-aot#24]
给集中式页面配置补充一些功能建议：
1. 能够配置公共的`config`。因为在实际使用过程中，有很多页面要用到相同的第三方小程序组件，如果在每个页面的`config`里写`usingComponents`太繁琐了。
2. 能够在页面级组件`mpType: 'page'`里配置`config`，即：
- xx.vue
``` js
export default {
  mpType: 'page',
  config: {
    ...
  }
}
```

优先级：页面vue组件的 config > 页面的 config > 公共的 config，并且三者会合并。

来源：https://github.com/kaola-fed/megalo-aot/issues/12#issuecomment-442293841

**Comment by F-loat** [comment]
很赞，建议在 App.vue 中通过以下方式指定公共 config，每次提取后缓存起来，和其他页面的配置进行合并

``` vue
<config global>
...
</config>
```

页面的 config 属性我这边做过一个[实现](https://github.com/F-loat/mpvue-config-loader)，只能支持静态代码解析，如果要支持 mixin 之类的估计会复杂很多，而且不是太有必要，有公共配置应该基本就可以满足需求了

**Comment by fengzilong** [comment]
我也是这么想的，有个项目级别的公用 config，拿来和 page 的 config 进行合并基本就够用了

**Comment by b2nil** [comment]
`config` 可以支持一下用 `yaml` 来写。
```yaml
<config lang='yaml'>
---   
pages:
    - pages/index
subpackages:
    -
     root: packageA
     pages:
     	- pages/test
    -
     root: pages/packageB
     pages:
     	- pages/test
window:
    backgroundTextStyle: light
    navigationBarBackgroundColor: '#fff'
    navigationBarTitleText: demo
    navigationBarTextStyle: black
</config>
```
