### ISSUE TITLE
css内容的tag selector编译有误

### ISSUE THREAD

**Issue by owlikesj** [kaola-fed/megalo-aot#63]
发现 @megalo/target 0.5.6版本的 postcss-plugin没有正确识别tag selector
比如下面的keyframes代码
```css
@-webkit-keyframes load {
  0% {
    opacity: 1;
  }

  100% {
    opacity: 0.2;
  }
}
```
会被编译成
```css
@-webkit-keyframes load {
._0% {
    opacity: 1;
}
._100% {
    opacity: 0.2;
}
}
```
导致报错
