### ISSUE TITLE
无法使用标签选择器

### ISSUE THREAD

**Issue by b2ns** [kaola-fed/megalo-aot#78]
看了下实现，在@megalo/target//lib/postcss-plugins/tag-selector-transform.js中默认将标签选择器都变成了._xxx这样的类选择器，这导致无法在小程序中利用标签选择器进行全局样式的重置，当项目中还要兼顾仍使用小程序语法的页面时情况就更糟。:<

```css
/* reset.less */

/* input */
view, text {
  line-height: 1;
}
button::after {
  border: none;
}

/* output */
._view, ._text {
  line-height: 1;
}
._button::after {
  border: none;
}
```
